name: task1
on: [push]

jobs:
  print-txt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v4
      
      - run: echo "$(cat hello_world.txt)"

